"""
Equation cheat sheet data.
Served via GET /api/cheatsheet/data — fetched by the frontend on load.
LaTeX uses double-backslash (\\) which serializes correctly through JSON to the browser.
"""

CHEAT_DATA = {
    "loss": [
        {
            "name": "MAE",
            "eq": "\\text{MAE} = \\frac{1}{n}\\sum_{i=1}^{n}|y_i - \\hat{y}_i|",
            "symbols": "$y_i$: true value, $\\hat{y}_i$: predicted, $n$: samples",
            "used": "Regression; robust to outliers; same units as target",
            "tag": "linear_regression",
            "note": "Gradient is constant $\\pm 1/n$ regardless of error size. Use when outliers are present.",
        },
        {
            "name": "MSE",
            "eq": "\\text{MSE} = \\frac{1}{n}\\sum_{i=1}^{n}(y_i - \\hat{y}_i)^2",
            "symbols": "$y_i$: true, $\\hat{y}_i$: predicted, $n$: samples",
            "used": "Regression; penalizes large errors heavily; smooth gradient",
            "tag": "linear_regression",
            "note": "Gradient: $\\frac{-2}{n}(y_i - \\hat{y}_i)$. Sensitive to outliers due to squaring.",
        },
        {
            "name": "RMSE",
            "eq": "\\text{RMSE} = \\sqrt{\\frac{1}{n}\\sum_{i=1}^{n}(y_i - \\hat{y}_i)^2}",
            "symbols": "$y_i$: true, $\\hat{y}_i$: predicted",
            "used": "Same units as target; most interpretable regression metric",
            "tag": "linear_regression",
        },
        {
            "name": "Binary Cross-Entropy",
            "eq": "L = -\\frac{1}{n}\\sum_{i=1}^{n}[y_i\\log(\\hat{p}_i) + (1-y_i)\\log(1-\\hat{p}_i)]",
            "symbols": "$y_i \\in \\{0,1\\}$: label, $\\hat{p}_i$: predicted probability from sigmoid",
            "used": "Binary classification; logistic regression; sigmoid output layer",
            "tag": "cross_entropy",
            "note": "Derived from MLE assuming Bernoulli. When $y=1$: $-\\log(\\hat{p})$; when $y=0$: $-\\log(1-\\hat{p})$.",
        },
        {
            "name": "Categorical Cross-Entropy",
            "eq": "L = -\\sum_{c=1}^{C} y_c \\log(\\hat{p}_c)",
            "symbols": "$C$: classes, $y_c$: one-hot label, $\\hat{p}_c$: softmax probability",
            "used": "Multiclass classification; softmax output layer",
            "tag": "cross_entropy",
            "note": "For one-hot labels simplifies to $-\\log(\\hat{p}_{\\text{correct}})$. Combined with softmax: gradient $= \\hat{p}_c - y_c$.",
        },
        {
            "name": "KL Divergence",
            "eq": "D_{KL}(P \\| Q) = \\sum_{x} P(x) \\log\\frac{P(x)}{Q(x)}",
            "symbols": "$P$: true distribution, $Q$: approximation; not symmetric",
            "used": "VAEs, knowledge distillation, measuring distribution distance",
            "tag": "mle",
            "note": "Relation to cross-entropy: $H(P,Q) = H(P) + D_{KL}(P\\|Q)$. Minimizing CE = minimizing KL from true distribution.",
        },
        {
            "name": "Hinge Loss",
            "eq": "L = \\frac{1}{n}\\sum_{i=1}^{n}\\max(0,\\; 1 - y_i \\cdot \\hat{y}_i)",
            "symbols": "$y_i \\in \\{-1,+1\\}$: label, $\\hat{y}_i$: raw model score (not probability)",
            "used": "Support Vector Machines; max-margin classifiers",
            "tag": "regularization",
        },
        {
            "name": "L1 Regularization (Lasso)",
            "eq": "L_{\\text{total}} = L_{\\text{task}} + \\lambda\\sum_{j}|w_j|",
            "symbols": "$\\lambda$: strength, $w_j$: weights",
            "used": "Sparse weights; automatic feature selection",
            "tag": "regularization",
            "note": "Gradient: $\\text{sign}(w_j)$ — constant push toward 0, can reach exactly 0 → sparsity.",
        },
        {
            "name": "L2 Regularization (Ridge)",
            "eq": "L_{\\text{total}} = L_{\\text{task}} + \\lambda\\sum_{j}w_j^2",
            "symbols": "$\\lambda$: strength, $w_j$: weights",
            "used": "Shrinks all weights; weight decay in optimizers",
            "tag": "regularization",
            "note": "Gradient: $2\\lambda w_j$ — proportional push, never exactly 0 → dense but small weights.",
        },
    ],

    "metrics": [
        {
            "name": "Accuracy",
            "eq": "\\text{Acc} = \\frac{TP + TN}{TP + TN + FP + FN}",
            "symbols": "$TP$: true pos, $TN$: true neg, $FP$: false pos, $FN$: false neg",
            "used": "Balanced classes only — misleading on imbalanced data",
            "tag": "class_imbalance",
        },
        {
            "name": "Precision",
            "eq": "P = \\frac{TP}{TP + FP}",
            "symbols": "$TP$: true pos, $FP$: false pos",
            "used": "Minimize false positives (spam filter, fraud alerts)",
            "tag": "class_imbalance",
            "note": "Of all predicted positives, how many are actually positive?",
        },
        {
            "name": "Recall (Sensitivity / TPR)",
            "eq": "R = \\frac{TP}{TP + FN}",
            "symbols": "$TP$: true pos, $FN$: false neg",
            "used": "Minimize false negatives (cancer detection, fraud detection)",
            "tag": "class_imbalance",
            "note": "Of all actual positives, how many did we catch?",
        },
        {
            "name": "F1 Score",
            "eq": "F_1 = \\frac{2 \\cdot P \\cdot R}{P + R} = \\frac{2TP}{2TP + FP + FN}",
            "symbols": "$P$: precision, $R$: recall",
            "used": "Imbalanced classes; balances precision-recall tradeoff",
            "tag": "class_imbalance",
            "note": "Harmonic mean of P and R. Punishes extreme imbalance between P and R harder than arithmetic mean.",
        },
        {
            "name": "F-beta Score",
            "eq": "F_\\beta = (1+\\beta^2)\\frac{P \\cdot R}{\\beta^2 P + R}",
            "symbols": "$\\beta > 1$: weight recall more; $\\beta < 1$: weight precision more",
            "used": "When you want to tune precision/recall tradeoff explicitly",
            "tag": "class_imbalance",
        },
        {
            "name": "Specificity (TNR)",
            "eq": "\\text{Spec} = \\frac{TN}{TN + FP}",
            "symbols": "$TN$: true neg, $FP$: false pos",
            "used": "Medical tests; true negative rate",
            "tag": "class_imbalance",
        },
        {
            "name": "Confusion Matrix",
            "eq": "\\begin{pmatrix} TP & FN \\\\ FP & TN \\end{pmatrix}",
            "symbols": "Rows: actual class. Columns: predicted class. Diagonal = correct predictions",
            "used": "Classification overview — see all error types at once",
            "tag": "class_imbalance",
            "note": "Heat map visualization reveals which classes get confused. Off-diagonal = errors.",
        },
        {
            "name": "ROC-AUC",
            "eq": "\\text{AUC} = \\int_0^1 TPR\\; d(FPR)",
            "symbols": "$TPR$: recall, $FPR = FP/(FP+TN)$: false positive rate",
            "used": "Binary classification; threshold-independent; robust to class imbalance",
            "tag": "class_imbalance",
            "note": "AUC = 0.5: random classifier. AUC = 1.0: perfect. Measures ranking quality regardless of threshold.",
        },
        {
            "name": "Top-K Accuracy",
            "eq": "\\text{Top-K Acc} = \\frac{1}{n}\\sum_{i=1}^{n} \\mathbf{1}[y_i \\in \\text{top-}k(\\hat{p}_i)]",
            "symbols": "$k$: number of top predictions checked, $y_i$: true label",
            "used": "Multiclass with many classes (ImageNet top-5); retrieval tasks",
            "tag": "class_imbalance",
        },
        {
            "name": "MRR",
            "eq": "\\text{MRR} = \\frac{1}{|Q|}\\sum_{i=1}^{|Q|}\\frac{1}{\\text{rank}_i}",
            "symbols": "$\\text{rank}_i$: rank of first relevant result for query $i$, $|Q|$: total queries",
            "used": "Information retrieval, QA systems, search ranking",
            "tag": "concept_drift",
        },
        {
            "name": "Log Loss (Multiclass)",
            "eq": "\\text{LogLoss} = -\\frac{1}{n}\\sum_{i}\\sum_{c} y_{ic}\\log(\\hat{p}_{ic})",
            "symbols": "$y_{ic}$: one-hot label, $\\hat{p}_{ic}$: predicted prob for class $c$",
            "used": "Probabilistic classifiers; penalizes confident wrong predictions heavily",
            "tag": "cross_entropy",
        },
    ],

    "activations": [
        {
            "name": "Sigmoid",
            "eq": "\\sigma(x) = \\frac{1}{1+e^{-x}}",
            "symbols": "output $\\in (0,1)$; not zero-centered",
            "used": "Binary output layer; logistic regression",
            "tag": "backprop",
            "note": "Derivative: $\\sigma'(x) = \\sigma(x)(1-\\sigma(x))$. Max = 0.25. Saturates → vanishing gradients in deep nets.",
        },
        {
            "name": "Tanh",
            "eq": "\\tanh(x) = \\frac{e^x - e^{-x}}{e^x + e^{-x}}",
            "symbols": "output $\\in (-1,1)$; zero-centered",
            "used": "RNNs/LSTMs; better than sigmoid for hidden layers",
            "tag": "backprop",
            "note": "Derivative: $1 - \\tanh^2(x)$. Zero-centered helps gradient flow. Still saturates for large $|x|$.",
        },
        {
            "name": "ReLU",
            "eq": "\\text{ReLU}(x) = \\max(0, x)",
            "symbols": "output $\\in [0, \\infty)$; sparse activation",
            "used": "Default for hidden layers in CNNs and MLPs; fast, no saturation for $x>0$",
            "tag": "vanishing_gradient",
            "note": "Derivative: 1 if $x>0$, else 0. Dying ReLU: neuron stuck at 0 if it always receives negative input.",
        },
        {
            "name": "Leaky ReLU",
            "eq": "f(x) = \\max(\\alpha x,\\; x), \\quad \\alpha = 0.01",
            "symbols": "$\\alpha$: small fixed slope for negative inputs (e.g. 0.01)",
            "used": "Fix for dying ReLU; preserves small gradient for negative inputs",
            "tag": "vanishing_gradient",
        },
        {
            "name": "PReLU",
            "eq": "f(x) = \\max(\\alpha x,\\; x), \\quad \\alpha \\text{ learned}",
            "symbols": "$\\alpha$: learned parameter trained via backprop",
            "used": "Adaptive version of Leaky ReLU; $\\alpha$ adapts to data",
            "tag": "vanishing_gradient",
            "note": "Same form as Leaky ReLU but $\\alpha$ is trainable. Minimal parameter overhead.",
        },
        {
            "name": "ELU",
            "eq": "f(x) = \\begin{cases} x & x > 0 \\\\ \\alpha(e^x-1) & x \\leq 0 \\end{cases}",
            "symbols": "$\\alpha > 0$ controls saturation for negative values (typically 1.0)",
            "used": "Smooth negative region; pushes mean activation toward zero",
            "tag": "vanishing_gradient",
        },
        {
            "name": "GELU",
            "eq": "\\text{GELU}(x) = x \\cdot \\Phi(x) \\approx x \\cdot \\sigma(1.702x)",
            "symbols": "$\\Phi(x)$: Gaussian CDF; gates input by its own probability",
            "used": "BERT, GPT, ViT — standard in transformers; smoother than ReLU",
            "tag": "attention",
            "note": "Stochastic interpretation: $x \\cdot P(X \\leq x),\\; X \\sim \\mathcal{N}(0,1)$. Differentiable everywhere unlike ReLU.",
        },
        {
            "name": "Swish",
            "eq": "\\text{Swish}(x) = x \\cdot \\sigma(\\beta x)",
            "symbols": "$\\sigma$: sigmoid, $\\beta$: learnable or fixed to 1",
            "used": "EfficientNet, modern nets; often beats ReLU on deeper models",
            "tag": "attention",
        },
        {
            "name": "Softmax",
            "eq": "\\text{softmax}(z_i) = \\frac{e^{z_i}}{\\sum_{j=1}^{K} e^{z_j}}",
            "symbols": "$z_i$: logit for class $i$, $K$: num classes; outputs sum to 1",
            "used": "Multiclass output layer; converts logits to probabilities",
            "tag": "cross_entropy",
            "note": "Numerically stable: subtract $\\max(z)$ before exp. Combined with CE: gradient $= \\hat{p}_c - y_c$.",
        },
    ],

    "gradients": [
        {
            "name": "Gradient Descent",
            "eq": "\\theta \\leftarrow \\theta - \\alpha \\nabla_{\\theta} L",
            "symbols": "$\\theta$: parameters, $\\alpha$: learning rate, $\\nabla_\\theta L$: gradient of loss",
            "used": "Iterative optimization of any differentiable loss",
            "tag": "gradient_descent",
            "note": "Batch GD: full dataset. SGD: 1 sample (noisy). Mini-batch (default): batch size $B$ balances both.",
        },
        {
            "name": "SGD + Momentum",
            "eq": "v \\leftarrow \\beta v - \\alpha \\nabla L; \\quad \\theta \\leftarrow \\theta + v",
            "symbols": "$v$: velocity, $\\beta$: momentum coefficient (e.g. 0.9)",
            "used": "Escapes local minima; smoother convergence than vanilla SGD",
            "tag": "gradient_descent",
        },
        {
            "name": "Adam Optimizer",
            "eq": "\\theta_t = \\theta_{t-1} - \\frac{\\alpha \\hat{m}_t}{\\sqrt{\\hat{v}_t}+\\epsilon}",
            "symbols": "$\\hat{m}_t$: bias-corrected 1st moment, $\\hat{v}_t$: 2nd moment, $\\epsilon=10^{-8}$",
            "used": "Default optimizer for deep learning; adaptive per-parameter learning rates",
            "tag": "adam_optimizer",
            "note": "1st moment: $m_t = \\beta_1 m_{t-1} + (1{-}\\beta_1)g_t$. 2nd moment: $v_t = \\beta_2 v_{t-1} + (1{-}\\beta_2)g_t^2$. Bias correction: $\\hat{m}_t = m_t/(1{-}\\beta_1^t)$. Defaults: $\\beta_1=0.9$, $\\beta_2=0.999$.",
        },
        {
            "name": "Chain Rule (Backprop)",
            "eq": "\\frac{\\partial L}{\\partial w} = \\frac{\\partial L}{\\partial a} \\cdot \\frac{\\partial a}{\\partial z} \\cdot \\frac{\\partial z}{\\partial w}",
            "symbols": "$L$: loss, $a$: activation output, $z$: pre-activation, $w$: weight",
            "used": "Core of backpropagation — gradient flows backward through layers",
            "tag": "backprop",
            "note": "For a linear layer $z = Wx + b$: $\\partial z/\\partial W = x^T$. Gradient of $L$ w.r.t. $W$ = (upstream gradient) $\\cdot x^T$.",
        },
        {
            "name": "Backprop: Regression (MSE)",
            "eq": "\\frac{\\partial L}{\\partial W} = \\frac{-2}{n} X^T (y - \\hat{y})",
            "symbols": "$X$: inputs, $y$: true labels, $\\hat{y} = Xw$: predictions",
            "used": "Linear regression gradient; set to 0 → normal equations",
            "tag": "backprop",
            "note": "Derivation: $L = \\frac{1}{n}\\|y-Xw\\|^2 \\Rightarrow \\nabla_w L = \\frac{-2}{n}X^T(y-Xw)$. Setting $=0$ gives closed form.",
        },
        {
            "name": "Backprop: Classification (CE + Softmax)",
            "eq": "\\frac{\\partial L}{\\partial z_c} = \\hat{p}_c - y_c",
            "symbols": "$z_c$: logit for class $c$, $\\hat{p}_c$: softmax output, $y_c$: one-hot label",
            "used": "Multiclass classification — gradient of CE w.r.t. logits",
            "tag": "backprop",
            "note": "Elegant result: gradient = prediction error. For correct class: $\\hat{p}_c - 1$. For others: $\\hat{p}_c$.",
        },
        {
            "name": "Gradient Clipping",
            "eq": "g \\leftarrow g \\cdot \\frac{\\tau}{\\|g\\|} \\quad \\text{if } \\|g\\| > \\tau",
            "symbols": "$g$: gradient vector, $\\|g\\|$: L2 norm, $\\tau$: threshold (e.g. 1.0 or 5.0)",
            "used": "RNNs and transformers; prevents exploding gradients",
            "tag": "exploding_gradient",
        },
        {
            "name": "Vanishing Gradient",
            "eq": "\\frac{\\partial L}{\\partial w_1} = \\prod_{k=2}^{L}\\frac{\\partial h_k}{\\partial h_{k-1}} \\cdot \\frac{\\partial L}{\\partial h_L}",
            "symbols": "$h_k$: activations at layer $k$; product of Jacobians shrinks exponentially",
            "used": "Deep sigmoid/tanh nets; explains why ReLU, BatchNorm, ResNets were invented",
            "tag": "vanishing_gradient",
            "note": "Sigmoid max derivative = 0.25. With $L$ layers: gradient $\\propto 0.25^L \\to 0$. Fix: ReLU, batch norm, skip connections, LSTM gates.",
        },
        {
            "name": "Batch Normalization",
            "eq": "\\hat{x} = \\frac{x - \\mu_B}{\\sqrt{\\sigma_B^2 + \\epsilon}}, \\quad y = \\gamma\\hat{x} + \\beta",
            "symbols": "$\\mu_B, \\sigma_B^2$: batch mean/variance; $\\gamma, \\beta$: learned scale and shift",
            "used": "Between linear and activation layers; faster training, allows higher LR",
            "tag": "batch_norm",
            "note": "At inference: use running mean/variance accumulated during training (not batch stats).",
        },
    ],

    "linalg": [
        {
            "name": "Linear Regression",
            "eq": "\\hat{y} = Xw + b",
            "symbols": "$X \\in \\mathbb{R}^{n \\times d}$: inputs, $w \\in \\mathbb{R}^d$: weights, $b$: bias",
            "used": "Supervised regression; baseline for all ML",
            "tag": "linear_regression",
            "example": "3 data points: $(1,2),(2,4),(3,5)$. With $w=1.5, b=0.5$: predictions $\\hat{y}_1=2, \\hat{y}_2=3.5, \\hat{y}_3=5$.",
        },
        {
            "name": "Closed-Form OLS",
            "eq": "w^* = (X^T X)^{-1} X^T y",
            "symbols": "$X$: input matrix, $y$: target vector; requires $X^TX$ invertible",
            "used": "Small datasets with $n > d$; exact solution, no iteration",
            "tag": "linear_regression",
            "note": "Numerically unstable when $X^TX$ near-singular. Fix: $(X^TX + \\lambda I)^{-1}X^Ty$ (ridge).",
            "example": "$$X = \\begin{pmatrix}1&1\\\\1&2\\\\1&3\\end{pmatrix},\\; y = \\begin{pmatrix}2\\\\3\\\\5\\end{pmatrix}$$ $X^TX = \\begin{pmatrix}3&6\\\\6&14\\end{pmatrix}$, solution $w^* \\approx \\begin{pmatrix}0.33\\\\1.5\\end{pmatrix}$ so $\\hat{y} = 0.33 + 1.5x$.",
        },
        {
            "name": "Matrix Multiply",
            "eq": "(AB)_{ij} = \\sum_{k=1}^{p} A_{ik} B_{kj}",
            "symbols": "$A \\in \\mathbb{R}^{m \\times p}$, $B \\in \\mathbb{R}^{p \\times n}$, result $\\in \\mathbb{R}^{m \\times n}$",
            "used": "Linear layers, attention scores, PCA projections — everywhere",
            "tag": "linear_algebra_basics",
            "note": "Not commutative: $AB \\neq BA$. Transpose: $(AB)^T = B^T A^T$.",
            "example": "$$\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}\\begin{pmatrix}5&6\\\\7&8\\end{pmatrix} = \\begin{pmatrix}19&22\\\\43&50\\end{pmatrix}$$ Row 1 × Col 1: $1{\\cdot}5+2{\\cdot}7=19$. Inner dims must match: $(m{\\times}p)(p{\\times}n)=(m{\\times}n)$.",
        },
        {
            "name": "Eigendecomposition",
            "eq": "A = Q \\Lambda Q^{-1}, \\quad Av = \\lambda v",
            "symbols": "$Q$: eigenvectors (columns), $\\Lambda$: diagonal eigenvalues, $v$: eigenvector, $\\lambda$: eigenvalue",
            "used": "PCA covariance matrix; symmetric $A \\Rightarrow Q$ orthogonal",
            "tag": "eigendecomposition",
            "note": "Only for square matrices. Symmetric matrices always have real eigenvalues + orthogonal eigenvectors.",
            "example": "$$A = \\begin{pmatrix}3&1\\\\1&3\\end{pmatrix}$$ Eigenvalues (solve $\\det(A-\\lambda I)=0$): $\\lambda_1=4, \\lambda_2=2$. Eigenvectors: $v_1=\\frac{1}{\\sqrt{2}}\\begin{pmatrix}1\\\\1\\end{pmatrix},\\; v_2=\\frac{1}{\\sqrt{2}}\\begin{pmatrix}1\\\\-1\\end{pmatrix}$. $A$ stretches $v_1$ by 4×, $v_2$ by 2×.",
        },
        {
            "name": "SVD",
            "eq": "A = U \\Sigma V^T",
            "symbols": "$U$: left singular vectors, $\\Sigma$: diagonal singular values, $V$: right singular vectors",
            "used": "PCA, dimensionality reduction, pseudoinverse; works on any $m \\times n$ matrix",
            "tag": "svd",
            "note": "Truncated SVD (top-$k$): best rank-$k$ approximation by Eckart-Young theorem.",
            "example": "$$A = \\begin{pmatrix}3&0\\\\0&2\\\\0&0\\end{pmatrix}$$ Already diagonal: $\\sigma_1=3, \\sigma_2=2$. Rank-1 approx: keep only $\\sigma_1$ → captures $9/(9+4) \\approx 69\\%$ of variance.",
        },
        {
            "name": "PCA via SVD",
            "eq": "X = U\\Sigma V^T \\;\\Rightarrow\\; Z = XV_k = U_k\\Sigma_k",
            "symbols": "$V_k$: top-$k$ right singular vectors (principal components), $Z$: projected data",
            "used": "Dimensionality reduction; visualization; decorrelate features",
            "tag": "svd_pca",
            "note": "Variance explained by component $i$: $\\sigma_i^2 / \\sum_j \\sigma_j^2$. Center data first.",
            "example": "4 points: $\\{(2,0),(0,1),(-2,0),(0,-1)\\}$. SVD gives $\\sigma_1=2$ (horizontal), $\\sigma_2=1$ (vertical). Project to 1D: $Z=[2,0,-2,0]$. Variance explained: $4/(4+1)=80\\%$.",
        },
        {
            "name": "Cosine Similarity",
            "eq": "\\cos(\\theta) = \\frac{a \\cdot b}{\\|a\\|\\|b\\|}",
            "symbols": "$a, b$: vectors, $\\theta$: angle; output $\\in [-1, 1]$",
            "used": "Embedding similarity (NLP, search, RAG); scale-invariant",
            "tag": "attention",
            "example": "$a=[1,0],\\; b=[1,1]$. Dot: $1$. $\\|a\\|=1$, $\\|b\\|=\\sqrt{2}$. $\\cos\\theta = 1/\\sqrt{2} \\approx 0.707$, so $\\theta=45°$. Identical vectors → 1.0; orthogonal → 0.",
        },
        {
            "name": "L1 / L2 / L∞ Norms",
            "eq": "\\|x\\|_1 = \\sum_i |x_i|, \\quad \\|x\\|_2 = \\sqrt{\\sum_i x_i^2}, \\quad \\|x\\|_\\infty = \\max_i |x_i|",
            "symbols": "$x$: vector of any dimension",
            "used": "L1: sparsity. L2: Euclidean distance / regularization. L∞: worst-case bound",
            "tag": "norms",
            "example": "$x=[3,4]$: $\\|x\\|_1=7$, $\\|x\\|_2=\\sqrt{9+16}=5$ (3-4-5 triangle!), $\\|x\\|_\\infty=4$.",
        },
        {
            "name": "Scaled Dot-Product Attention",
            "eq": "\\text{Attention}(Q,K,V) = \\text{softmax}\\!\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V",
            "symbols": "$Q,K,V$: query/key/value matrices, $d_k$: key dimension",
            "used": "Transformers; self-attention; cross-attention in encoder-decoder",
            "tag": "attention",
            "note": "Without $\\sqrt{d_k}$: softmax saturates → vanishing gradients. Scaling keeps variance $\\approx 1$.",
            "example": "$q=[1,0],\\; k_1=[1,0],\\; k_2=[0,1],\\; d_k=2$. Scores: $[1/\\sqrt{2},\\; 0]$. After softmax: $[0.62, 0.38]$. Query attends mostly to similar key.",
        },
        {
            "name": "Dot Product",
            "eq": "a \\cdot b = \\sum_i a_i b_i = \\|a\\|\\|b\\|\\cos\\theta",
            "symbols": "$\\theta$: angle between $a$ and $b$; result = 0 if orthogonal",
            "used": "Attention scores, projections, similarity measures",
            "tag": "attention",
            "example": "$a=[1,2,3],\\; b=[4,5,6]$. $a{\\cdot}b = 4+10+18=32$. $\\cos\\theta = 32/(\\sqrt{14}\\cdot\\sqrt{77}) \\approx 0.976$ — nearly aligned.",
        },
    ],
}
