import json
from pathlib import Path
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from core.questions import get_question
from core.question_generator import (
    serve_or_generate,
    pick_topic_from_progress,
    get_generated_question,
)

router = APIRouter()
PROGRESS_FILE = Path(__file__).parent.parent / "data" / "progress.json"


def load_progress() -> dict:
    if PROGRESS_FILE.exists():
        return json.loads(PROGRESS_FILE.read_text())
    return {"sessions": [], "weak_spots": {}}


class DrillResponse(BaseModel):
    question_id: int
    question_text: str
    tag: str
    difficulty: str
    hint: str = ""
    source: str = "Generated"


@router.get("/drill", response_model=DrillResponse)
def get_drill_question(tag: str = Query(default=None)):
    """
    Return the next drill question.
    All questions are generated by Claude API and cached.
    Hardcoded questions are preserved but not served here.
    """
    progress = load_progress()
    topic = tag if tag else pick_topic_from_progress(progress)
    q = serve_or_generate(topic, progress)
    return DrillResponse(
        question_id=q["id"],
        question_text=q["text"],
        tag=q["tag"],
        difficulty=q["difficulty"],
        hint=q.get("hint", ""),
        source=q.get("source", "Generated"),
    )


@router.get("/drill/{question_id}", response_model=DrillResponse)
def get_specific_question(question_id: int):
    """Fetch a specific question by ID — checks hardcoded bank first, then generated cache."""
    # Check hardcoded bank (used by Study Guide failure links)
    q = get_question(question_id)
    if q is None:
        # Check generated cache
        q = get_generated_question(question_id)
    if q is None:
        raise HTTPException(status_code=404, detail="Question not found")
    return DrillResponse(
        question_id=q["id"],
        question_text=q["text"],
        tag=q["tag"],
        difficulty=q["difficulty"],
        hint=q.get("hint", ""),
        source=q.get("source", "Generated"),
    )


@router.get("/questions")
def list_questions():
    """Returns all hardcoded questions (for reference/admin use)."""
    from core.questions import get_all_questions
    return get_all_questions()
